project:
  type: website

website:
  title: "PHC 6099: R Computing for Health Sciences"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



